---
# defaults for dev-ivantory

is_permitted: false
divan_skip_prepare: false

divan_repo: please_change_me
divan_branch: main
divan_dir: "{{ ansible_user_dir }}/devel/ivantory"

# same as in the dev-ansible role
divan_venv_dir: "{{ ansible_user_dir }}/.ansible/venv"

divan_cipher: aes-256-cbc
divan_password: ""
divan_check_file: ""
divan_check_phrase: ""

divan_roles_dir: "{{ ansible_user_dir }}/devel/galaxy"
divan_roles_list_file: "{{ divan_dir }}/requirements.yml"
divan_roles_check_role: ivansible.lin_base

divan_venv_link: "{{ divan_dir }}/.venv"
divan_requirements_file: "{{ divan_dir }}/ansible-requirements.txt"
divan_requirements_link: "{{ divan_venv_dir |dirname }}/ivantory-requirements.txt"

divan_galaxy_token: ""

divan_cryptor_exe: /usr/local/bin/transcrypt.sh
divan_cryptor_configured_flag: ""

dev_ansible_link_dir: "{{ ansible_user_dir }}/bin"
divan_linked_binaries:
  - play
  - role
  - cryptor
  - vultr
  - gitroles
  - lin-enter

git_hub_release: latest
git_hub_dir: "/usr/local/hub/hub-linux-{{ lin_apt_arch }}-{{ git_hub_release }}"
git_hub_remake_links: false
git_hub_binary: /usr/local/bin/hub
git_hub_man_dir: /usr/local/share/man/man1
git_hub_completion_dir: /etc/bash_completion.d
...
